[project]
name = "financial-transaction-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asgiref==3.8.1",
    "django==5.2.1",
    "django-allauth==65.8.0",
    "django-htmx==1.23.0",
    "sqlparse==0.5.3",
]
