# Generated by Django 5.2.1 on 2025-05-14 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'category', 'month', 'year'], name='transaction_user_id_5c818a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'name', 'type', 'category', 'created_at'], name='transaction_user_id_cd37da_idx'),
        ),
    ]
