# Generated by Django 5.2.1 on 2025-05-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_budget_transaction_user_id_5c818a_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
    ]
