# Generated by Django 5.2.1 on 2025-05-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_budget_month_alter_budget_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
